language: python

python:
  - '2.7'
  - '3.4'

before_install:
  - pip install --upgrade coveralls pip
  - sudo apt-get install -y mercurial
  - sudo apt-get build-dep -y pygame
  - pip install hg+http://bitbucket.org/pygame/pygame

script: "python setup.py test"

after_success:
  - coveralls

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
